### ISSUE TITLE
Syntax error in installation file.

### ISSUE THREAD

**Issue by hydrosIII** [0x1fff/docker-informix#1]
Hi, i have found a sintax error in your bash install script, when you execute the script i get:

informix_install.sh: line 182: /var/informix//ifx_dev.env: No such file or directory
chown: cannot access `/var/informix//ifx_dev.env': No such file or directory 

There is an extra slash in the script.

It should be :in line 182:

cat <<EOF > "${USER_HOME}"ifx_${INSTANCE_NAME}.env

in line 200:

chown informix: "${USER_HOME}ifx_${INSTANCE_NAME}.env"

**Comment by 0x1fff** [comment]
This is strange. AFAIR the // in path shouldn't be issue in most Linux distributions (especially Debian based), but I have fixed it - try updating to newest commit, delete previously created docker-informix images and rebuild it from scratch:

here is sample output on my machine:

```
   ....
   ....
   ....
   >>>    Create group and user for Informix
   >>>    Uncompress Informix Archive: iif.12.10.FC4DE.linux-x86_64.tar
   >>>    Launch silent install ...
   >>>    Postconfig onconfig ...
   >>>    Postconfig sqlhost ...
   >>>    Include tcp support ...
   >>>    Create informix user environnement
   >>>    Chown Informix binary directory structure
   >>>    Create data directory
   >>>    Deleting unpacked files
   >>>    Deleting downloaded packages
   ###############################################
   #         Installation completed              #
   ###############################################
```

Here is log from starting Informix database:

```
>>>    Create data directory structure in /home/informix/data (ifx initialization)
>>>    Create user "test"...
>>>    Starting up the IBM Informix Database (dev) ... 
*** Startup of dev SUCCESS ***
>>>    Create database "test"...
>>>    Grant DBA to database "test" for user "test"...
IBM Informix Dynamic Server Version 12.10.FC4DE Software Serial Number AAA#B000000
    #################################################
    # Informix container login information:          
    #   database:    test                  
    #   user:        test                  
    #   password:    test                  
    #################################################
```

If bug is fixed please close this issue or write me a comment to close this. If my changes won't fix bug, please provide me some details (stdot/stderr from building docker container, docker version etc.).

**Comment by hydrosIII** [comment]
Hi, i'm using debian wheezy, but i'm using your script to install informix in the system and not inside a container, it saved me some work, thank you. It is curious that in other parts of the script, or other scripts like, the start-database.sh the double slash does work.  However the bug is still valid. Thank you for fixing it.  I will create a fork of your repo, for the installation scripts in your system. Thanks.

**Comment by 0x1fff** [comment]
hi, In recent commit I have added ability to change username/groupname and uid/gid in installation script. It may be useful in your use case ;).
